<a href="https://colab.research.google.com/github/2303A52097/AIML_2303A52097/blob/main/ASSESMENT_1_PART3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 3 Access Data from Various Data Sources using builtin Func
tion of Numpy, Pandas[CO3]
 1. Generate your own dataset using MS Excel and Notepad to prepare the dataset. Save
 it in Google Drive and access it in Google Colab.
 2. Upload the text le using tab seperated value(.tsv) and access the data from the le.
 3. Upload the text le using comma seperated value(.csv) and access the data from le.
 4. Access the excel le using .xlsx
 5. Access the text from the URL

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df1 = pd.read_table("/content/drive/MyDrive/reethi.txt")
df1

           hii reethi
0  this is your friend
1                 bye
2     nice to meet you

In [ ]:
data2 = pd.read_csv("/content/drive/MyDrive/customers-100.csv")
data2

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,25-03-2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,02-06-2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [10]:
data3 = pd.read_excel("/content/drive/MyDrive/file_example_XLSX_50.xlsx")
data3

     0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125